name: Build & Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Build
        run: go build ./cmd/lazy

      - name: Tag
        run: |
          TAG="v0.0.1"
          git tag $TAG
          git push origin $TAG

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: lazy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
